### ISSUE TITLE
单文件行数超过3000就会报错

### ISSUE THREAD

**Issue by PAULWONGHZ** [EmmyLua/VSCode-EmmyLua#101]
单文件行数超过3000就会报错，报错之后编辑器就特别卡

���� 31, 2022 8:08:56 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.util.ConcurrentModificationException
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.tang.vscode.api.impl.Folder.findFile(Folder.kt:47)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:307)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:294)
	at com.tang.vscode.LuaTextDocumentService$updateAnnotators$1.invoke(LuaTextDocumentService.kt:58)
	at com.tang.vscode.LuaTextDocumentService$updateAnnotators$1.invoke(LuaTextDocumentService.kt:57)
	at com.tang.vscode.utils.UtilsKt.computeAsync$lambda-0(utils.kt:141)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	... 6 more

���� 31, 2022 8:08:56 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.util.ConcurrentModificationException
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.tang.vscode.api.impl.Folder.findFile(Folder.kt:47)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:307)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:294)
	at com.tang.vscode.LuaTextDocumentService$foldingRange$1.invoke(LuaTextDocumentService.kt:995)
	at com.tang.vscode.LuaTextDocumentService$foldingRange$1.invoke(LuaTextDocumentService.kt:994)
	at com.tang.vscode.utils.UtilsKt.computeAsync$lambda-0(utils.kt:141)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	... 6 more

[Error - 20:08:56] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.tang.vscode.api.impl.Folder.findFile(Folder.kt:47)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:307)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:294)
	at com.tang.vscode.LuaTextDocumentService$foldingRange$1.invoke(LuaTextDocumentService.kt:995)
	at com.tang.vscode.LuaTextDocumentService$foldingRange$1.invoke(LuaTextDocumentService.kt:994)
	at com.tang.vscode.utils.UtilsKt.computeAsync$lambda-0(utils.kt:141)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	... 6 more

**Comment by CppCXY** [comment]
看起来是折叠出了问题
