### ISSUE TITLE
插件日常诊断错误

### ISSUE THREAD

**Issue by CppCXY** [EmmyLua/VSCode-EmmyLua#106]
���� 22, 2022 1:49:52 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 51
���� 22, 2022 1:49:54 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 53
���� 22, 2022 1:49:54 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 54
���� 22, 2022 1:50:10 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.util.ConcurrentModificationException
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.tang.vscode.api.impl.Folder.findFile(Folder.kt:47)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:363)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:350)
	at com.tang.vscode.LuaTextDocumentService$diagnostic$1.invoke(LuaTextDocumentService.kt:1077)
	at com.tang.vscode.LuaTextDocumentService$diagnostic$1.invoke(LuaTextDocumentService.kt:1076)
	at com.tang.vscode.utils.UtilsKt.computeAsync$lambda-0(utils.kt:141)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Error - 13:50:10] Request textDocument/diagnostic failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.tang.vscode.api.impl.Folder.findFile(Folder.kt:47)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:363)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:350)
	at com.tang.vscode.LuaTextDocumentService$diagnostic$1.invoke(LuaTextDocumentService.kt:1077)
	at com.tang.vscode.LuaTextDocumentService$diagnostic$1.invoke(LuaTextDocumentService.kt:1076)
	at com.tang.vscode.utils.UtilsKt.computeAsync$lambda-0(utils.kt:141)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

[Error - 13:50:10] Document pull failed for text document 
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.tang.vscode.api.impl.Folder.findFile(Folder.kt:47)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:363)
	at com.tang.vscode.LuaWorkspaceService.findFile(LuaWorkspaceService.kt:350)
	at com.tang.vscode.LuaTextDocumentService$diagnostic$1.invoke(LuaTextDocumentService.kt:1077)
	at com.tang.vscode.LuaTextDocumentService$diagnostic$1.invoke(LuaTextDocumentService.kt:1076)
	at com.tang.vscode.utils.UtilsKt.computeAsync$lambda-0(utils.kt:141)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more

���� 22, 2022 1:50:24 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 75
���� 22, 2022 1:50:24 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 79

**Comment by galencw** [comment]
Is this bug solved？
This bug still occurs frequently on my computer, causing EmmyLua to freeze for a long time.
Is there a solution to this problem?

**Comment by CppCXY** [comment]
> 请问这个bug有解决吗？ 我还是会经常遇到这个bug，每次这个Error出现EmmyLua 就是卡顿一段时间，还蛮影响使用的。 有什么解决办法吗？

已经不打算解决vscode上关于语言服务的问题了, 正在重新写一个[语言服务](https://github.com/CppCXY/EmmyLuaAnalyzer)
