### ISSUE TITLE
VSCode error:  Request textDocument/completion failed. Message: Internal error. Code: -32603 

### ISSUE THREAD

**Issue by romanTrufanov** [EmmyLua/VSCode-EmmyLua#123]
Hi there!

I use EmmyLua for pretty big project and since last month I started to get error:

**Error msg notification:**

![image](https://user-images.githubusercontent.com/79691083/229017556-3ee6ecdf-2455-4527-a93a-d29ce56ba2ba.png)

Does anybody know how to solve it? Thanks, in advance!

**Full log from extension here:**

```
[Error - 9:30:34 AM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.StackOverflowError
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:67)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:59)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:69)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:57)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:81)
	at com.intellij.psi.impl.source.tree.AstBufferUtil$BufferVisitor.visitComposite(AstBufferUtil.java:116)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:126)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:41)
	at com.intellij.psi.impl.source.tree.AstBufferUtil.toBuffer(AstBufferUtil.java:36)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:257)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:221)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:138)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.resolveType(LuaDocPsiImplUtil.kt:54)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:253)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocGeneralTyImpl.getType(LuaDocGeneralTyImpl.java:40)
	at com.tang.intellij.lua.ty.TyDocGeneric.initBaseTy(TyGeneric.kt:98)
	at com.tang.intellij.lua.ty.TyDocGeneric.<init>(TyGeneric.kt:101)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:272)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocGenericTyImpl.getType(LuaDocGenericTyImpl.java:40)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:341)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocTagAliasImpl.getType(LuaDocTagAliasImpl.java:80)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)
	at com.tang.intellij.lua.ty.TyClass.substitute(TyClass.kt:320)
	at com.tang.intellij.lua.ty.TyUnion.substitute(TyUnion.kt:49)
	at com.tang.intellij.lua.ty.TyGeneric.substitute(TyGeneric.kt:88)
	at com.tang.intellij.lua.ty.TySerializedClass.recoverAlias(TyClass.kt:452)
	at com.tang.intellij.lua.ty.TyAliasSubstitutor.substitute(TySubstitutor.kt:133)

	........................
	
Mar 31, 2023 9:30:46 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 35123

```

**Environment:**

VSCode 

```
Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z (2 wks ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

```

Extension:

```
Version: EmmyLua v0.5.13
Published: 1/13/2019, 14:47:38
Last released: 3/16/2023, 18:23:08

```

**Comment by vbogomazov-ms** [comment]
Yep, it's crashing from time to time

**Comment by CppCXY** [comment]
vscode-emmylua has many underlying issues, and as someone who picked up the project, I don't have the capacity to solve all these problems. Alternatively, you can solve the issues yourself and submit a PR. my current focus is on another project, [ls2](https://github.com/CppCXY/EmmyLua-LanguageServer2).
