### ISSUE TITLE
EmmyLua 0.7.7 crash

### ISSUE THREAD

**Issue by SmartAIHub** [EmmyLua/VSCode-EmmyLua#161]
at EmmyLua.CodeAnalysis.Compilation.Search.Members+<FindMember>d__26.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, Boolean ByRef)
   at EmmyLua.CodeAnalysis.Compilation.Search.Declarations.InnerDeclaration(EmmyLua.CodeAnalysis.Syntax.Node.LuaSyntaxElement)
   at EmmyLua.CodeAnalysis.Compilation.Search.Declarations.FindDeclaration(EmmyLua.CodeAnalysis.Syntax.Node.LuaSyntaxElement)
   at EmmyLua.CodeAnalysis.Compilation.Infer.ExpressionInfer.InferExpr(EmmyLua.CodeAnalysis.Syntax.Node.SyntaxNodes.LuaExprSyntax, EmmyLua.CodeAnalysis.Compilation.Search.SearchContext)
   at EmmyLua.CodeAnalysis.Compilation.Search.ElementInfer.InferCore(EmmyLua.CodeAnalysis.Syntax.Node.LuaSyntaxElement)
   at EmmyLua.CodeAnalysis.Compilation.Search.ElementInfer.Infer(EmmyLua.CodeAnalysis.Syntax.Node.LuaSyntaxElement)
   at System.Linq.Enumerable+SelectListIterator`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable.All[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at EmmyLua.CodeAnalysis.Compilation.Analyzer.ResolveAnalyzer.ResolveDependencyGraph.CalcDependency()
   at EmmyLua.CodeAnalysis.Compilation.Analyzer.ResolveAnalyzer.ResolveDependencyGraph.Resolve(System.Collections.Generic.List`1<EmmyLua.CodeAnalysis.Compilation.Analyzer.UnResolved>)
   at EmmyLua.CodeAnalysis.Compilation.Analyzer.ResolveAnalyzer.ResolveAnalyzer.Analyze(EmmyLua.CodeAnalysis.Compilation.Analyzer.AnalyzeContext)
   at EmmyLua.CodeAnalysis.Compilation.LuaCompilation.AnalyzeDirtyDocuments()
   at EmmyLua.CodeAnalysis.Compilation.LuaCompilation.AddSyntaxTrees(System.Collections.Generic.IEnumerable`1<System.ValueTuple`2<EmmyLua.CodeAnalysis.Document.LuaDocumentId,EmmyLua.CodeAnalysis.Syntax.Tree.LuaSyntaxTree>>)
   at EmmyLua.CodeAnalysis.Workspace.LuaWorkspace.LoadMainWorkspace(System.String)
   at EmmyLua.LanguageServer.Server.ServerContext.StartServer(OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams)
   at EmmyLua.LanguageServer.Server.ServerContext+<StartServerAsync>d__41.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[EmmyLua.LanguageServer.Server.ServerContext+<StartServerAsync>d__41, EmmyLua.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[EmmyLua.LanguageServer.Server.ServerContext+<StartServerAsync>d__41, EmmyLua.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[EmmyLua.LanguageServer.Server.ServerContext+<StartServerAsync>d__41, EmmyLua.LanguageServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider+<GetConfiguration>d__25.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider+<GetConfiguration>d__25, OmniSharp.Extensions.LanguageServer, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider+<GetConfiguration>d__25, OmniSharp.Extensions.LanguageServer, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider+<GetConfiguration>d__25, OmniSharp.Extensions.LanguageServer, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at OmniSharp.Extensions.JsonRpc.ResponseRouter+ResponseRouterReturnsImpl+<Returning>d__4`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.JsonRpc.ResponseRouter+ResponseRouterReturnsImpl+<Returning>d__4`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], OmniSharp.Extensions.JsonRpc, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.JsonRpc.ResponseRouter+ResponseRouterReturnsImpl+<Returning>d__4`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], OmniSharp.Extensions.JsonRpc, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.JsonRpc.ResponseRouter+ResponseRouterReturnsImpl+<Returning>d__4`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], OmniSharp.Extensions.JsonRpc, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at OmniSharp.Extensions.JsonRpc.InputHandler+<>c__DisplayClass36_0.<HandleRequest>b__2(System.IObserver`1<System.Reactive.Unit>)
   at System.Reactive.Linq.QueryLanguage+CreateWithDisposableObservable`1[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].SubscribeCore(System.IObserver`1<System.Reactive.Unit>)
   at System.Reactive.ObservableBase`1[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].ScheduledSubscribe(System.Reactive.AutoDetachObserver`1<System.Reactive.Unit>)
   at System.Reactive.Concurrency.Scheduler+<>c__75`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ScheduleAction>b__75_0(System.Reactive.Concurrency.IScheduler, System.ValueTuple`2<System.Action`1<System.__Canon>,System.__Canon>)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ValueTuple`2<System.__Canon,System.__Canon>, System.TimeSpan, System.Func`3<System.Reactive.Concurrency.IScheduler,System.ValueTuple`2<System.__Canon,System.__Canon>,System.IDisposable>)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ValueTuple`2<System.__Canon,System.__Canon>, System.Func`3<System.Reactive.Concurrency.IScheduler,System.ValueTuple`2<System.__Canon,System.__Canon>,System.IDisposable>)
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reactive.Concurrency.IScheduler, System.__Canon, System.Action`1<System.__Canon>)
   at System.Reactive.ObservableBase`1[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Subscribe(System.IObserver`1<System.Reactive.Unit>)
   at System.ObservableExtensions.SubscribeSafe[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]](System.IObservable`1<System.Reactive.Unit>, System.IObserver`1<System.Reactive.Unit>)
   at System.Reactive.Linq.ObservableImpl.ConcatMany`1+ConcatManyOuterObserver[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Drain()
   at System.Reactive.Linq.ObservableImpl.ConcatMany`1+ConcatManyOuterObserver[[System.Reactive.Unit, System.Reactive, Version=6.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].OnNext(System.IObservable`1<System.Reactive.Unit>)
   at System.Reactive.Subjects.Subject`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnNext(System.__Canon)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(System.Buffers.ReadOnlySequence`1<Byte> ByRef)
   at OmniSharp.Extensions.JsonRpc.InputHandler+<ProcessInputStream>d__35.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.JsonRpc.InputHandler+<ProcessInputStream>d__35, OmniSharp.Extensions.JsonRpc, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.JsonRpc.InputHandler+<ProcessInputStream>d__35, OmniSharp.Extensions.JsonRpc, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[OmniSharp.Extensions.JsonRpc.InputHandler+<ProcessInputStream>d__35, OmniSharp.Extensions.JsonRpc, Version=0.19.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]].ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
[Error - 11:35:36] The EmmyLua plugin for vscode. server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:35:36] Server process exited with code 3221225725.

**Comment by SmartAIHub** [comment]
0.8.0 has been resolved. Thank you
