### ISSUE TITLE
0.4.10 更新后仍然无法使用self.

### ISSUE THREAD

**Issue by foreversos** [EmmyLua/VSCode-EmmyLua#93]
![newgif](https://user-images.githubusercontent.com/3012313/161378518-51896bbf-367b-4457-8903-1ae0b077bc97.gif)

[log.txt](https://github.com/EmmyLua/VSCode-EmmyLua/files/8402296/log.txt)

 详细的看TXT
 
控制台JAVA有报错:
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
��Ϣ: Unsupported notification method: $/setTrace
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 3
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 7
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
��Ϣ: Unsupported notification method: $/setTrace
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
��Ϣ: Unsupported notification method: $/setTrace
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
��Ϣ: Unsupported notification method: $/setTrace
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
��Ϣ: Unsupported notification method: $/setTrace
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 17
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 15
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 16
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 25
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 34
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 35
���� 02, 2022 6:03:03 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 13
���� 02, 2022 6:03:20 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.StackOverflowError
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.StackOverflowError
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getContainingFile(ASTDelegatePsiElement.java:52)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:37)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:41)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:27)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:170)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:58)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:58)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:63)

**Comment by CppCXY** [comment]
看起来很正常啊
![image](https://user-images.githubusercontent.com/40318218/161390019-e551d206-7459-41fb-8a26-e9ab0a6cf034.png)

**Comment by foreversos** [comment]
我这边单独新建LUA,写简单结构有也可以
但是在复杂的我自己老的文件就不行
肯定是我这边个例,但是不知道怎么解决...

**Comment by CppCXY** [comment]
如果无法正常工作可以试试退到0.4.1如果没有这个问题我会排查我这边的问题

**Comment by foreversos** [comment]
好的,感谢解答
